[[constraint]]
  name = "github.com/Masterminds/goutils"
  version = "1.0.1"

[[constraint]]
  name = "github.com/Masterminds/semver"
  version = "1.4.0"

[[constraint]]
  name = "github.com/huandu/xstrings"
  version = "1.0.0"

[[constraint]]
  name = "github.com/imdario/mergo"
  version = "0.3.2"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[prune]
  go-tests = true
  unused-packages = true
